name: hexlet-ci-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup project
        run: make setup
      - name: run lint
        run: make lint
      - name: run tests
        run: make tests
