name: hexlet-ci-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup project
        run: make setup
      - name: run lint
        run: make lint
      - name: run tests
        run: make tests
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.31e2a4c8-b704-4d0c-b8e9-764b1d01db2e }}
